config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#home'
  resources :jilbo, only: [:index, :show] do
    post 'upload', on: :collection
  end
  resources :chep, only: [:index, :show] do
    post 'upload', on: :collection
  end
  resources :halsted, only: [:index, :show] do
    post 'upload', on: :collection
  end
  post 'upload' => 'dashboard#upload', as: :upload

end

app/models/halsted.rb
class Halsted < ActiveRecord::Base

	OPERATORS = %w(+= -= *= /= %= &= |= ^= >>>= <<= >>= ++ -- != == ! >= <= >>> << >> > < && || instanceof return ~ & | ^ = + - * / %)

	validate :check_content

	after_create :add_content, :init

	def check_content
		return true unless compile
		errors_path = Rails.root.join(File.dirname(path_file), 'errors.txt').to_s
		pid = Process.spawn('javac', path_file, err: errors_path)
		Process.waitpid(pid)
		errors_file = File.open(errors_path).read
		if errors_file != ''
			errors.add(:File, "Your code is uncompilible")
			false
		else 
			true
		end
	end

	def add_content
		self.content = File.open(path_file).read
		self.save!
	end

	def prepare_code(scip = true)
		src = content.clone
		src.gsub!(/(\/\*([^*]|[\r\n]|(\*+([^*\/]|[\r\n])))*\*+\/)|(\/\/.*)/, '')
		src.gsub!(/\b(int|boolean|double|float|char|long|short)\b.+?;/, '')
		src.gsub!(/\b(void|int|boolean|double|float|char|long|short)\b.+/, '')
		src.gsub!(/(["])(?:(?=(\\?))\2.)*?\1/, '') if scip
		src
	end

	def find_conditions_loops_switch
		code = prepare_code
		hash = Hash.new(0)
		code.scan(/(\bif\b)|([^?\r\n]*)\?([^:]*):([^;]*)/).flatten.compact.each { |match| hash[match.to_s] += 1 }
		code.scan(/\b(for)|(while)|(switch)\b/).flatten.compact.each { |match| hash[match.to_s] += 1 }
		code.scan(/\b(break)|(continue)\b/).flatten.compact.each { |match| hash[match.to_s] += 1 }
		hash
	end	

	def find_count_govno
		code = prepare_code
		hash = Hash.new(0)
		code.scan(/,|\.|:|;/).flatten.compact.each { |match| hash[match.to_s] += 1 }
		code.scan(/\w+\(.*\)/).flatten.compact.each { |match| match.gsub!(/\(.*\)/, '(..)'); hash[match.to_s] += 1 }
		code.gsub!(/\w+\(.*\)/, '')
		for_if_while_swith_count = code.scan(/\b(for)|(while)|(switch)|(if)\b/).flatten.compact.count
		brackets = code.scan(/\(/).count - for_if_while_swith_count
		hash["(..)"] += brackets if brackets > 0
		code.scan(/\]/).each { |match| hash["[..]"] += 1 }
		code.scan(/\}/).each { |match| hash["{..}"] += 1 }
		hash
	end

	def find_count_ebutchee_govno
		code = prepare_code
		hash = Hash.new 0
		OPERATORS.each do |op|
			code.scan(op).each { |match| hash[match.to_s] += 1 }
			code.gsub!(op, '')
		end
		hash
	end

	def find_variables
		keywords = %w{ 
			byte short int long char float double boolean
			if else switch case default while do break continue for
			try catch finally throw throws
			private protected public
			import package class interface extends implements static final void abstract native
			new return this super
			synchronized volatile
			const goto instanceof enum assert transient strictfp
		}
		code = prepare_code false
		code.gsub!(/\w+\(/, '')
		hash = Hash.new(0)
		code.scan(/\".+\"/).each do |match|
			hash[match.to_s] += 1 unless keywords.include?(match)
		end
		code.gsub!(/\".+\"/)
		code.scan(/\w+/).each do |match|
			hash[match.to_s] += 1 unless keywords.include?(match)
		end
		hash
	end

	def init
		hash_oprs = find_conditions_loops_switch.merge(find_count_govno).merge(find_count_ebutchee_govno)
		hash_opds = find_variables
		self.operators = hash_oprs.to_json.to_s
		self.operands = hash_opds.to_json.to_s
		self.uniq_operators = hash_oprs.size
		self.uniq_operands = hash_opds.size
		self.count_operators = hash_oprs.values.reduce(:+)
		self.count_operands = hash_opds.values.reduce(:+)
		self.save!
	end

end

app/controllers/halsted_controller.rb
class HalstedController < ApplicationController

	def index
		@java_file = Halsted.new
		@java_files = Halsted.all
	end

	def show
		@java_file = Halsted.find(params[:id])
	end

	def upload
		@java_file = Halsted.new
		@java_files = Halsted.all
		uploaded_io = java_file_params[:path_file]
		new_path_file = Rails.root.join('java_files', uploaded_io.original_filename)
		File.open(new_path_file, 'wb') do |file|
			file.write(uploaded_io.read)
		end
		if @java_file.update(path_file: new_path_file, compile: java_file_params[:compile])
			redirect_to halsted_path(@java_file)
		else 
			render :index
		end
	end

	private 

	def java_file_params
		params.require(:halsted).permit(:path_file, :compile)
	end

end

app/helpers/halsted_helper.rb
module HalstedHelper
end

app/views/halsted/_errors_messages.html.slim
- if @java_file.errors.any?
	.alert.alert-danger@alert
		strong Errors:
		ul
			- @java_file.errors.full_messages.each do |msg|
				li = msg

app/views/halsted/index.html.slim
h3 Halsted metrics

.table-responsive
	table.table
		thead
			tr
				th #
				th Title
				th
					| n
					sub 1
				th 
					| N
					sub 1
				th
					| n
					sub 2
				th 
					| N
					sub 2
		tbody
			- @java_files.each_with_index do |item, i|
				tr
					td = i + 1
					td
						a href=halsted_path(item) = File.basename(item.path_file) + '  #id = ' + item.id.to_s
					td = item.uniq_operators
					td = item.count_operators
					td = item.uniq_operands
					td = item.count_operands

.center-block
	h4 Add file
	= form_for @java_file, url: upload_halsted_index_path, method: :post, multipart: true, html: { class: "form-horizontal" } do |f|
		= render 'errors_messages'

		
		.form_group
			= f.label "Compilible?", class: "col-xs-2"
			= f.check_box :compile
		
		.form_group
			= f.label :file, class: "col-xs-2"
			= f.file_field :path_file, reqiured: true
		
		.form_group	
			= f.submit "Send", class: "btn btn-default"

app/views/halsted/show.html.slim
h3
	strong 
		| Halsted file : 
		= File.basename @java_file.path_file
.row
	p
		| Cловарь программы : 
		strong 
			| n = 
			= a = @java_file.uniq_operators
			|  + 
			= b = @java_file.uniq_operands
			|  = 
			= c = a + b
	p
		| Длина программы : 
		strong 
			| N = 
			= a = @java_file.count_operators
			|  + 
			= b = @java_file.count_operands
			|  = 
			= d = a + b
	p 
		| Объем программы : 
		strong 
			| V = 
			= d
			|  log
			sub 2
			= c
			|  ~ 
			= (d * (Math.log(c) / Math.log(2))).round 2

.row
	.col-sm-8.col-md-6
		table.table.table-bordered
			thead
				tr
					th j
					th Operators
					th 
						| f
						sub 1j
			tbody
				- puts @java_file.operators
				- hash_oprs = JSON.parse(@java_file.operators)
				- num = 1
				- hash_oprs.each do |key, value|
					tr
						td = num
						- num += 1
						td = key
						td = value
			tfoot
				tr 
				 	td 
				 		strong
					 		| n
					 		sub 1
					 		| =
					 		= @java_file.uniq_operators
				 	td
				 	td 
				 		strong 
				 			| N
				 			sub 1
				 			| = 
				 			= @java_file.count_operators
	.col-sm-8.col-md-6
		table.table.table-bordered
			thead
				tr
					th i
					th Operands
					th 
						| f
						sub 2j
			tbody
				- puts @java_file.operands
				- hash_oprs = JSON.parse(@java_file.operands)
				- num = 1
				- hash_oprs.each do |key, value|
					tr
						td = num
						- num += 1
						td = key
						td = value
			tfoot
				tr 
				 	td 
				 		strong
					 		| n
					 		sub 2
					 		| =
					 		= @java_file.uniq_operands
				 	td
				 	td 
				 		strong 
				 			| N
				 			sub 2
				 			| = 
				 			= @java_file.count_operands
.row
	- code = @java_file.content 
	pre = Simplabs::Highlight.highlight(:java, code).html_safe