config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#home'
  resources :jilbo, only: [:index, :show] do
    post 'upload', on: :collection
  end
  resources :chep, only: [:index, :show] do
    post 'upload', on: :collection
  end
  resources :halsted, only: [:index, :show] do
    post 'upload', on: :collection
  end
  post 'upload' => 'dashboard#upload', as: :upload

end

app/controllers/chep_controller.rb
class ChepController < ApplicationController

	def index
		@java_file = JavaFile.new
		@java_files = JavaFile.all.where(chep: true)
	end

	def show
		@java_file = JavaFile.find(params[:id])
	end

	def upload
		@java_file = JavaFile.new
		@java_files = JavaFile.all.where(chep: true)
		uploaded_io = java_file_params[:path_file]
		new_path_file = Rails.root.join('java_files', uploaded_io.original_filename)
		File.open(new_path_file, 'wb') do |file|
			file.write(uploaded_io.read)
		end
		if @java_file.update(path_file: new_path_file, compile: java_file_params[:compile], chep: true)
			redirect_to chep_path(@java_file)
		else 
			render :index
		end
	end

	private 

	def java_file_params
		params.require(:java_file).permit(:path_file, :compile)
	end

end

app/helpers/chep_helper.rb
module ChepHelper
end

app/views/chep/index.html.slim
h3 Chepin metrics

.table-responsive
	table.table
		thead
			tr
				th #
				th Title
				th P
				th M
				th C
				th T
				th Q
				th Spens
		tbody
			- @java_files.each_with_index do |item, i|
				- hash = JSON.parse(item.role)
				tr
					td = i + 1
					td
						a href=chep_path(item) = File.basename(item.path_file) + '  #id = ' + item.id.to_s
					td = hash['p']
					td = hash['m']
					td = hash['c']
					td = hash['t']
					td = item.chep_metric
					td = item.spens

.center-block
	h4 Add file
	= form_for @java_file, url: upload_chep_index_path, method: :post, multipart: true, html: { class: "form-horizontal" } do |f|
		= render 'errors_messages'
	
		.form_group
			= f.label "Compilible?", class: "col-xs-2"
			= f.check_box :compile
		
		.form_group
			= f.label :file, class: "col-xs-2"
			= f.file_field :path_file, reqiured: true
		
		.form_group	
			= f.submit "Send", class: "btn btn-default"

app/views/chep/show.html.slim
.table-responsive
	table.table
		thead
			tr
				th #
				th Title
				th P
				th M
				th C
				th T
				th Q
				th Spens
		tbody
			- item = @java_file
			- hash = JSON.parse(item.role)
			tr
				td = item.id
				td
					a href=chep_path(item) = File.basename(item.path_file) + '  #id = ' + item.id.to_s
				td = hash['p']
				td = hash['m']
				td = hash['c']
				td = hash['t']
				td = item.chep_metric
				td = item.spens
	b Spens
	table.table
		thead
			- hash_spens = item.send(:spens_hash)	
			tr
				- hash_spens.each_key { |k| 
				th = k 
				- }
		tbody
			tr
				- hash_spens.each_value { |v| 
				td = v 
				- }
- code = @java_file.content 
pre = Simplabs::Highlight.highlight(:java, code).html_safe