config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#home'
  resources :jilbo, only: [:index, :show] do
    post 'upload', on: :collection
  end
  resources :chep, only: [:index, :show] do
    post 'upload', on: :collection
  end
  resources :halsted, only: [:index, :show] do
    post 'upload', on: :collection
  end
  post 'upload' => 'dashboard#upload', as: :upload

end

app/controllers/jilbo_controller.rb
class JilboController < ApplicationController

	def index
		@java_file = JavaFile.new
		@java_files = JavaFile.all.where(chep: false)
	end

	def show
		@java_file = JavaFile.find(params[:id])
	end

	def upload
		@java_file = JavaFile.new
		@java_files = JavaFile.all.where(chep: false)
		uploaded_io = java_file_params[:path_file]
		new_path_file = Rails.root.join('java_files', uploaded_io.original_filename)
		File.open(new_path_file, 'wb') do |file|
			file.write(uploaded_io.read)
		end
		if @java_file.update(path_file: new_path_file, compile: java_file_params[:compile])
			redirect_to jilbo_path(@java_file)
		else 
			render :index
		end
	end

	private 

	def java_file_params
		params.require(:java_file).permit(:path_file, :compile)
	end

end

app/helpers/jilbo_helper.rb
module JilboHelper
end

app/views/jilbo/index.html.slim
h3 Jilbo metrics

.table-responsive
	table.table
		thead
			tr
				th #
				th Title
				th Абсолютная сложность
				th Максимальный уровень вложенности
				th Относительная сложность
		tbody
			- @java_files.each_with_index do |item, i|
				tr
					td = i + 1
					td
						a href=jilbo_path(item) = File.basename(item.path_file) + '  #id = ' + item.id.to_s
					td = item.count_operators
					td = item.deepness
					td = item.cl

.center-block
	h4 Add file
	= form_for @java_file, url: upload_jilbo_index_path, method: :post, multipart: true, html: { class: "form-horizontal" } do |f|
		= render 'errors_messages'
	
		.form_group
			= f.label "Compilible?", class: "col-xs-2"
			= f.check_box :compile
		
		.form_group
			= f.label :file, class: "col-xs-2"
			= f.file_field :path_file, reqiured: true
		
		.form_group	
			= f.submit "Send", class: "btn btn-default"

app/views/jilbo/show.html.erb
<div class = "table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th># </th>
				<th>Title </th>
				<th>Абсолютная сложность</th>
				<th>Максимальный уровень вложенности</th>
				<th>Относительная сложность</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @java_file.id %></td>
				<td><%= File.basename(@java_file.path_file) %></td>
				<td><%= @java_file.count_operators %></td>
				<td><%= @java_file.deepness %></td>
				<td><%= @java_file.cl %></td>
			</tr>
		</tbody>
	</table>
</div>
<%- code = @java_file.content %>
<pre><%= Simplabs::Highlight.highlight(:java, code).html_safe %></pre>